### ISSUE TITLE
Password verification happens post full page rendering

### ISSUE THREAD

**Issue by bnf** [neuedaten/global_password#1]
The middleware first renders the full page and performs the password check afterwards. That could lead to a wrong assumption, about the "protection" of this global password. I guess your primary focus is control the visibility of the page – preventing certain action from being executed at all, might a focus for users of this extension.

IMO Checking the password should happen prior rendering the next middleware.
https://github.com/neuedaten/global_password/blob/a4c3b476194af2a4726d1e383e71151d518ad328/Classes/Middleware/CheckPassword.php#L43
This call should be the last call in your middleware (and only in case a valid password has been provided).

**Other hints:**

https://github.com/neuedaten/global_password/blob/a4c3b476194af2a4726d1e383e71151d518ad328/Classes/Middleware/CheckPassword.php#L42
The Annotation is wrong, you MUST not rely on receiving responses of type ` \TYPO3\CMS\Core\Http\Response` here, as another middleware (from another extension) is free to return another response class, as long as it implements `Psr\Http\Message\ResponseInterface`.

https://github.com/neuedaten/global_password/blob/a4c3b476194af2a4726d1e383e71151d518ad328/Classes/Middleware/CheckPassword.php#L58-L59
You should use the PSR-7 Request object (that is passed to your middleware) here, something like:

```
$request->getParsedBody()['global-password-submit'] ?? null;
// or If you really need to read from GET *and* Post, sth like:
$request->getParsedBody()['password'] ?? $request->getQueryParams()['password'] ?? null;
```

https://github.com/neuedaten/global_password/blob/a4c3b476194af2a4726d1e383e71151d518ad328/Classes/Middleware/CheckPassword.php#L79
You may improve this by rendering to a PSR-7 response
`return new \TYPO3\CMS\Core\Http\HtmlResponse($view->render());`

**Comment by r12r** [comment]
thanks for code review! I will check your points and optimize the extension.

**Comment by r12r** [comment]
done.
